import "dotenv/config";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { PRESETS } from "@/lib/presets/briefs";
import {
  runNamerPhase,
  runBrandScoutPhase,
  runFinishPhase,
} from "@/lib/orchestrator/workshop";
import { getLLMProvider, getSearchProvider, getImageProvider } from "@/lib/providers/factory";
import type { BrandKit } from "@/lib/agents/types";
import type { WorkshopEvent } from "@/lib/events/types";

async function main() {
  const out: Record<string, BrandKit> = {};
  for (const preset of PRESETS) {
    console.log(`Generating preset: ${preset.label}`);

    const noop = (_e: WorkshopEvent) => {};

    const namer = await runNamerPhase({
      brief: preset.brief,
      getLlm: getLLMProvider,
      emit: noop,
    });
    const chosenName = namer.top_pick;
    const brandScout = await runBrandScoutPhase({
      brief: preset.brief,
      chosenName,
      getLlm: getLLMProvider,
      getSearch: getSearchProvider,
      emit: noop,
    });
    const kit = await runFinishPhase({
      brief: preset.brief,
      chosenName,
      namerOutput: namer,
      brandScoutOutput: brandScout,
      getLlm: getLLMProvider,
      getSearch: getSearchProvider,
      getImage: getImageProvider,
      emit: noop,
    });
    out[preset.id] = kit;
  }

  await mkdir(path.resolve("public/demos"), { recursive: true });
  const fileContent = `// AUTO-GENERATED by scripts/generate-presets.ts. Do not edit by hand.
import type { BrandKit } from "@/lib/agents/types";
export const PRESET_KITS: Record<string, BrandKit> = ${JSON.stringify(out, null, 2)};
`;
  await writeFile(path.resolve("lib/presets/data.ts"), fileContent);
  console.log(`Wrote lib/presets/data.ts with ${Object.keys(out).length} kits.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
