import "dotenv/config";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { PRESETS } from "@/lib/presets/briefs";
import { runWorkshop } from "@/lib/orchestrator/workshop";
import { getLLMProvider, getSearchProvider, getImageProvider } from "@/lib/providers/factory";
import type { BrandKit } from "@/lib/agents/types";

async function main() {
  const out: Record<string, BrandKit> = {};
  for (const preset of PRESETS) {
    console.log(`Generating preset: ${preset.label}`);
    let kit: BrandKit | null = null;
    await runWorkshop({
      brief: preset.brief,
      getLlm: getLLMProvider,
      getSearch: getSearchProvider,
      getImage: getImageProvider,
      emit: (e) => { if (e.type === "brand_kit_ready") kit = e.brandKit; },
    });
    if (!kit) throw new Error(`Preset ${preset.id} failed`);
    out[preset.id] = kit;
  }

  await mkdir(path.resolve("public/demos"), { recursive: true });
  const fileContent = `// AUTO-GENERATED by scripts/generate-presets.ts. Do not edit by hand.
import type { BrandKit } from "@/lib/agents/types";
export const PRESET_KITS: Record<string, BrandKit> = ${JSON.stringify(out, null, 2)};
`;
  await writeFile(path.resolve("lib/presets/data.ts"), fileContent);
  console.log(`Wrote lib/presets/data.ts with ${Object.keys(out).length} kits.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
